name: Stale

on:
  schedule:
    - cron: "0 12 * * 0"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  stale:
    uses: forkwright/.github/.github/workflows/stale.yml@5556cb9e05327f855ccc208080fb1924cf7e8264
